chown qzmfrank:admin /usr/local/share/locale/be
chown qzmfrank:admin /usr/local/share/locale/be/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/ca
chown qzmfrank:admin /usr/local/share/locale/ca/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/da
chown qzmfrank:admin /usr/local/share/locale/da/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/de
chown qzmfrank:admin /usr/local/share/locale/de/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/el
chown qzmfrank:admin /usr/local/share/locale/el/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/eo
chown qzmfrank:admin /usr/local/share/locale/eo/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/es
chown qzmfrank:admin /usr/local/share/locale/es/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/fi
chown qzmfrank:admin /usr/local/share/locale/fi/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/fr
chown qzmfrank:admin /usr/local/share/locale/fr/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/hr
chown qzmfrank:admin /usr/local/share/locale/hr/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/id
chown qzmfrank:admin /usr/local/share/locale/id/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/ja
chown qzmfrank:admin /usr/local/share/locale/ja/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/nl
chown qzmfrank:admin /usr/local/share/locale/nl/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/ru
chown qzmfrank:admin /usr/local/share/locale/ru/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/sr
chown qzmfrank:admin /usr/local/share/locale/sr/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/sv
chown qzmfrank:admin /usr/local/share/locale/sv/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/tr
chown qzmfrank:admin /usr/local/share/locale/tr/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/uk
chown qzmfrank:admin /usr/local/share/locale/uk/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/vi
chown qzmfrank:admin /usr/local/share/locale/vi/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/zh_CN
chown qzmfrank:admin /usr/local/share/locale/zh_CN/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/locale/zh_TW
chown qzmfrank:admin /usr/local/share/locale/zh_TW/LC_MESSAGES
chown qzmfrank:admin /usr/local/share/man/de
chown qzmfrank:admin /usr/local/share/man/de/man1
