mv /usr/local/lib/libasan.0.dylib  	~/Codes/test/help-brew-test/
mv /usr/local/lib/libatomic.1.dylib	~/Codes/test/help-brew-test/
mv /usr/local/lib/libgcc_ext.10.4.dylib ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgcc_ext.10.5.dylib ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgcc_s.1.dylib      ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgcc_s.10.4.dylib   ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgcc_s.10.5.dylib   ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgfortran.3.dylib   ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgomp.1.dylib       ~/Codes/test/help-brew-test/
mv /usr/local/lib/libitm.1.dylib        ~/Codes/test/help-brew-test/
mv /usr/local/lib/libquadmath.0.dylib   ~/Codes/test/help-brew-test/
mv /usr/local/lib/libssp.0.dylib        ~/Codes/test/help-brew-test/
mv /usr/local/lib/libstdc++.6.dylib     ~/Codes/test/help-brew-test/
mv /usr/local/lib/libasan.la            ~/Codes/test/help-brew-test/
mv /usr/local/lib/libatomic.la          ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgfortran.la        ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgmp.la             ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgomp.la            ~/Codes/test/help-brew-test/
mv /usr/local/lib/libitm.la             ~/Codes/test/help-brew-test/
mv /usr/local/lib/libmpc.la             ~/Codes/test/help-brew-test/
mv /usr/local/lib/libmpfr.la            ~/Codes/test/help-brew-test/
mv /usr/local/lib/libquadmath.la        ~/Codes/test/help-brew-test/
mv /usr/local/lib/libssp.la             ~/Codes/test/help-brew-test/
mv /usr/local/lib/libssp_nonshared.la   ~/Codes/test/help-brew-test/
mv /usr/local/lib/libstdc++.la          ~/Codes/test/help-brew-test/
mv /usr/local/lib/libsupc++.la          ~/Codes/test/help-brew-test/
mv /usr/local/lib/libatomic.a           ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgfortran.a         ~/Codes/test/help-brew-test/
mv /usr/local/lib/libgomp.a             ~/Codes/test/help-brew-test/
mv /usr/local/lib/libiberty.a           ~/Codes/test/help-brew-test/
mv /usr/local/lib/libitm.a              ~/Codes/test/help-brew-test/
mv /usr/local/lib/libmpc.a              ~/Codes/test/help-brew-test/
mv /usr/local/lib/libmpfr.a             ~/Codes/test/help-brew-test/
mv /usr/local/lib/libquadmath.a         ~/Codes/test/help-brew-test/
mv /usr/local/lib/libssp.a              ~/Codes/test/help-brew-test/
mv /usr/local/lib/libssp_nonshared.a    ~/Codes/test/help-brew-test/
mv /usr/local/lib/libstdc++.a           ~/Codes/test/help-brew-test/
mv /usr/local/lib/libsupc++.a           ~/Codes/test/help-brew-test/

brew prune
